# Generated by Django 3.1.3 on 2020-11-28 22:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_opinions', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('coupon', models.CharField(max_length=255)),
                ('expiry_date', models.DateTimeField()),
                ('icon', models.ImageField(upload_to='')),
            ],
        ),
    ]
