# Generated by Django 3.1.3 on 2020-11-28 23:55

import apps.coupons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='icon',
            field=models.ImageField(upload_to=apps.coupons.models.get_file_path),
        ),
    ]
