version: "3.7"

services:
  frontend:
    build: ./frontend
    ports:
      - "8000:80"

  backend:
    build: ./backend
    ports:
      - "8080:8080"

  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  pgdata:
