------
server:
  servlet:
    context-path: /api/
  port: 8080
  url: http://vps-4663ca5b.vps.ovh.net:8080/api
  file:
    storage: /app/images
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: debug
spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  flyway:
    enabled: true
product:
  api:
    url: https://www.eprodukty.gs1.pl/api/v1/products/get_products/
  google:
    api:
      url: https://www.googleapis.com/customsearch/v1
      key: AIzaSyAycyYYOlOkxIhM177oyrdJYF49ZIwkGkA
      cx: 730a0e8d6f0408a77
