server:
  servlet:
    context-path: /api/
  port: 8080
  url:
  file:
    storage:

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: debug

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: wwf
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  flyway:
    enabled: true

product:
  api:
    url: https://www.eprodukty.gs1.pl/api/v1/products/get_products/
  google:
    api:
      url: https://www.googleapis.com/customsearch/v1
      key:
      cx: